### ISSUE TITLE
Configurable Project Overview member box visibility

### ISSUE THREAD

**Issue by sanak** [gtt-project/redmine_privacy#4]
**Problem**
Related with #3, currently Project Overview member box will be hidden when this plugin is installed.

**Improvement**
Allow to see Project Overview member box by configuration.
Probably, adding checkbox to each project settings will be better than system (global) level configuration.

**Comment by dkastl** [comment]
I think it would be best to add role-based permissions. Configuring this on a project level doesn't make so much sense to me.

**Comment by dkastl** [comment]
Was fixed in https://github.com/gtt-project/redmine_privacy/pull/12
